# Generated by Django 4.2.2 on 2023-06-20 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citasmd', '0002_doctor_paciente_citasmd_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='citasmd',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='citasmd.paciente'),
        ),
    ]
