# Generated by Django 4.2.2 on 2023-06-23 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citasmd', '0003_citasmd_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citasmd',
            name='id_citasmd',
        ),
    ]
